[package]
name = "pixie_zkvm"
version = "0.1.0"
edition = "2021"

[dependencies]
plonky2 = { git = "https://github.com/0xPolygonZero/plonky2" }
starky = { git = "https://github.com/0xPolygonZero/plonky2" }
anyhow = "1.0.86"
