name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  ensure_test:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Install Nextest
      run: cargo install cargo-nextest
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo nextest run --verbose
